# Java Maven CircleCI 2.0 configuration file
# using the maven orb: https://circleci.com/developer/orbs/orb/circleci/maven
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1

executors:
  j12:
    docker:
      - image: 'cimg/openjdk:12.0'

orbs:
  maven: circleci/maven@1.3.0

workflows:
  maven_test:
    jobs:
      # checkout, build, test, and upload test results
      - maven/test:
          executor: j12
