# Java Maven CircleCI 2.0 configuration file using a maven orb:
# https://circleci.com/developer/orbs/orb/circleci/maven
# try it
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1

orbs:
  maven: circleci/maven@1.3.0

workflows:
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results
